"""
Production-Ready Job-Resume Matching Agent
Built for: Hackathon Track A (Iron Man) - "Agent that works. Agent that lasts."

Following Tutorial 05 (Observability) Structure:
- LangSmith tracing for monitoring
- Proper error handling
- Simple, reliable schema
- Single run (no unnecessary loops)
"""

import os
import sys
import json
import time
import uuid
from pathlib import Path
from typing import List
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from datetime import datetime

# LangChain components
from langchain_core.messages import HumanMessage
from langsmith import Client

# Load environment
env_paths = [
    Path(__file__).parent.parent / '.env',
    Path('../.env'),
    Path('.env'),
]

for env_path in env_paths:
    if env_path.exists():
        load_dotenv(env_path)
        break

# Import Holistic AI Bedrock helper
parent_dir = Path(__file__).parent.parent
sys.path.insert(0, str(parent_dir / 'core'))

from react_agent.holistic_ai_bedrock import get_chat_model

print("✅ Holistic AI Bedrock helper loaded")


# ============================================
# Simple, Reliable Schema (LLM-Friendly)
# ============================================

class MatchScore(BaseModel):
    """Simple job-resume matching score - all fields generated by LLM"""

    # Overall assessment
    overall_score: int = Field(description="Overall match score 0-100", ge=0, le=100)
    recommendation: str = Field(description="Hire recommendation: Strong Yes, Yes, Maybe, No, or Strong No")
    confidence: int = Field(description="Confidence in assessment 0-100", ge=0, le=100)

    # Detailed scores
    skills_score: int = Field(description="Skills match score 0-100", ge=0, le=100)
    experience_score: int = Field(description="Experience match score 0-100", ge=0, le=100)
    education_score: int = Field(description="Education match score 0-100", ge=0, le=100)

    # Narrative analysis (LLM-generated text)
    skills_analysis: str = Field(description="Detailed analysis of skills match")
    experience_analysis: str = Field(description="Detailed analysis of experience match")
    education_analysis: str = Field(description="Detailed analysis of education match")

    # Summary lists
    strengths: List[str] = Field(description="Top 3-5 candidate strengths")
    weaknesses: List[str] = Field(description="Top 3-5 gaps or concerns")

    # Reasoning
    reasoning: str = Field(description="Overall reasoning for the recommendation")


# ============================================
# Main Matching Function
# ============================================

def match_job_resume(
    job_description: str,
    resume_data: dict,
    enable_tracing: bool = True
) -> tuple[MatchScore, dict]:
    """
    Match job description with resume and return score.

    Following observability tutorial pattern:
    - Single run (no loops)
    - LangSmith tracing enabled
    - Proper error handling
    - Metrics tracking

    Args:
        job_description: Job description text
        resume_data: Resume data dict from resume_agent.py
        enable_tracing: Enable LangSmith tracing

    Returns:
        Tuple of (MatchScore, metrics_dict)
    """

    # Generate run ID for tracing
    run_id = str(uuid.uuid4())

    print(f"\n{'='*70}")
    print("JOB-RESUME MATCHING AGENT")
    print(f"{'='*70}")
    print(f"Run ID: {run_id}")
    print(f"Tracing: {'Enabled' if enable_tracing and os.getenv('LANGSMITH_API_KEY') else 'Disabled'}")
    print()

    # Create LLM with structured output
    llm = get_chat_model("claude-3-5-sonnet")
    structured_llm = llm.with_structured_output(MatchScore)

    # Create comprehensive prompt
    resume_json = json.dumps(resume_data, indent=2)

    prompt = f"""You are an expert technical recruiter. Analyze how well this candidate matches the job requirements.

JOB DESCRIPTION:
{job_description}

CANDIDATE RESUME:
{resume_json}

Provide a comprehensive assessment with:
1. Overall score (0-100) based on job requirements
2. Detailed scores for skills, experience, and education
3. Clear textual analysis for each category
4. Top strengths and weaknesses
5. Hiring recommendation with reasoning

SCORING GUIDELINES:
- 90-100: Exceptional match, top 5% candidate
- 75-89: Strong match, recommend interview
- 60-74: Good match, consider for interview
- 40-59: Moderate match, significant gaps
- 0-39: Weak match, not a fit

RECOMMENDATIONS:
- "Strong Yes" (90+): Immediate interview
- "Yes" (75-89): Schedule interview
- "Maybe" (60-74): Review with team
- "No" (40-59): Pass unless exceptional
- "Strong No" (0-39): Not a fit

Be objective, data-driven, and specific in your analysis."""

    # Track performance
    start_time = time.time()

    try:
        # Set LangSmith tracing environment variables if enabled
        if enable_tracing and os.getenv('LANGSMITH_API_KEY'):
            if not os.getenv('LANGSMITH_TRACING'):
                os.environ['LANGSMITH_TRACING'] = 'true'

        # Invoke LLM directly with structured output
        # Use invoke instead of agent pattern to avoid compatibility issues
        message = HumanMessage(content=prompt)

        # Configure with metadata for LangSmith
        config = {
            "run_name": "job_resume_matching",
            "tags": ["job-matching", "production", "track-a"],
            "metadata": {
                "user_id": "demo_user",
                "model": "claude-3-5-sonnet",
                "task": "job_resume_matching",
                "version": "v2.0_observability",
                "environment": "production",
                "run_id": run_id
            }
        }

        # Invoke with structured output
        score = structured_llm.invoke(message, config=config)

        # Calculate metrics
        elapsed_ms = (time.time() - start_time) * 1000

        metrics = {
            'run_id': run_id,
            'latency_ms': elapsed_ms,
            'model': 'claude-3-5-sonnet',
            'status': 'success',
            'timestamp': datetime.now().isoformat()
        }

        # Display results
        print(f"{'='*70}")
        print("MATCHING RESULTS")
        print(f"{'='*70}\n")

        print(f"🎯 Overall Score: {score.overall_score}/100")
        print(f"📋 Recommendation: {score.recommendation}")
        print(f"🔒 Confidence: {score.confidence}%\n")

        print(f"📊 Score Breakdown:")
        print(f"  Skills:     {score.skills_score}/100")
        print(f"  Experience: {score.experience_score}/100")
        print(f"  Education:  {score.education_score}/100\n")

        print(f"🛠️  Skills Analysis:")
        print(f"  {score.skills_analysis}\n")

        print(f"💼 Experience Analysis:")
        print(f"  {score.experience_analysis}\n")

        print(f"🎓 Education Analysis:")
        print(f"  {score.education_analysis}\n")

        print(f"💪 Strengths:")
        for i, strength in enumerate(score.strengths, 1):
            print(f"  {i}. {strength}")

        print(f"\n⚠️  Weaknesses:")
        for i, weakness in enumerate(score.weaknesses, 1):
            print(f"  {i}. {weakness}")

        print(f"\n🤔 Reasoning:")
        print(f"  {score.reasoning}\n")

        # Performance metrics
        print(f"{'='*70}")
        print("PERFORMANCE METRICS")
        print(f"{'='*70}")
        print(f"⏱️  Latency: {metrics['latency_ms']:.2f}ms")
        print(f"🆔 Run ID: {metrics['run_id']}")
        print(f"✅ Status: {metrics['status']}")

        # LangSmith trace URL
        if enable_tracing and os.getenv('LANGSMITH_API_KEY'):
            try:
                ls_client = Client()
                # Search for run by metadata
                project = os.getenv('LANGSMITH_PROJECT', 'default')
                print(f"\n📊 View trace in LangSmith:")
                print(f"  https://smith.langchain.com")
                print(f"  Project: {project}")
                print(f"  Run ID: {run_id}")
            except Exception as e:
                print(f"\n📊 LangSmith tracing active (search by run_id: {run_id})")

        print(f"\n{'='*70}")
        print("✅ Matching complete!")
        print(f"{'='*70}\n")

        return score, metrics

    except Exception as e:
        elapsed_ms = (time.time() - start_time) * 1000

        print(f"❌ Error during matching: {e}\n")

        # Return error metrics
        metrics = {
            'run_id': run_id,
            'latency_ms': elapsed_ms,
            'model': 'claude-3-5-sonnet',
            'status': 'error',
            'error': str(e),
            'timestamp': datetime.now().isoformat()
        }

        raise Exception(f"Matching failed: {e}") from e


# ============================================
# Demo Function
# ============================================

def demo_matching():
    """Run matching demo following observability tutorial pattern"""

    print("\n" + "="*70)
    print("JOB-RESUME MATCHING - Production Demo")
    print("="*70)
    print("Following Tutorial 05 (Observability) structure")
    print("Features: LangSmith tracing, error handling, metrics tracking")
    print()

    # Check LangSmith
    if os.getenv('LANGSMITH_API_KEY'):
        print("✅ LangSmith tracing enabled")
        if not os.getenv('LANGSMITH_TRACING'):
            os.environ['LANGSMITH_TRACING'] = 'true'
        if not os.getenv('LANGSMITH_PROJECT'):
            os.environ['LANGSMITH_PROJECT'] = 'job-resume-matching'
    else:
        print("⚠️  LangSmith tracing disabled (no API key)")

    # Load job description
    job_desc_path = Path("track_a_iron_man/job_description_example.txt")
    if not job_desc_path.exists():
        print("\n❌ Job description not found!")
        print(f"   Expected: {job_desc_path.absolute()}")
        return

    with open(job_desc_path, 'r') as f:
        job_desc = f.read()

    print(f"📄 Loaded job description: {len(job_desc)} chars")

    # Load resume data
    resume_json_path = Path("track_a_iron_man/resume_extract.json")
    if not resume_json_path.exists():
        print("\n❌ Resume data not found!")
        print(f"   Expected: {resume_json_path.absolute()}")
        print("   Run resume_agent.py first to extract resume data")
        return

    with open(resume_json_path, 'r') as f:
        resume_data = json.load(f)

    print(f"📄 Loaded resume data: {len(json.dumps(resume_data))} chars\n")

    # Run matching (single run, as per tutorial pattern)
    try:
        score, metrics = match_job_resume(job_desc, resume_data, enable_tracing=True)

        print("Demo complete! Key takeaways:")
        print("  ✅ Single run (no unnecessary loops)")
        print("  ✅ LangSmith tracing for observability")
        print("  ✅ Simple schema (LLM-friendly)")
        print("  ✅ Comprehensive metrics tracking")
        print("  ✅ Proper error handling")

    except Exception as e:
        print(f"\n❌ Demo failed: {e}")
        print("\nThis demonstrates error handling - agent fails gracefully")


if __name__ == "__main__":
    demo_matching()
